### ISSUE TITLE
DESCRIPTION: Add URL and BugReports

### ISSUE THREAD

**Issue by HenrikBengtsson** [mgondan/rolog#1]
Hi, please consider adding fields URL and BugReports to your DESCRIPTION to make it easier to locate this repo from https://cran.r-project.org/package=rolog

**Comment by mgondan** [comment]
Dear Henrik,

Thank you for your suggestions, I will do accordingly. It will take some time until the next submission, but I expect 0.9.3 to be available in a month or so.

Best wishes,

Matthias






-------- Ursprüngliche Nachricht --------
Von: Henrik Bengtsson ***@***.***>
Datum: 30.04.22 03:00 (GMT+01:00)
An: mgondan/rolog ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [mgondan/rolog] DESCRIPTION: Add URL and BugReports (Issue #1)


Hi, please consider adding fields URL and BugReports to your DESCRIPTION to make it easier to locate this repo from https://cran.r-project.org/package=rolog
